### ISSUE TITLE
Compile error questions

### ISSUE THREAD

**Issue by AndreasSchutz** [PhilippMolitor/waveshare-rp2040-roundlcd-boilerplate#3]
Hi

Putting this question here as an issue... not sure if that is good...feel free to remove this if you dislike. My idea was that more could benefit from the answer.

I'm trying to extend my knowledge about the waveshare-rp2040-roundlcd.
When I try to compile your code after download, I get some compile errors that I can't fix in the LovyanGFX library.

----
.pio/libdeps/release/LovyanGFX/src/lgfx/v1/platforms/rp2040/common.cpp:78:56: error: use of enum 'gpio_function' without previous declaration
   78 |     bool lgfx_gpio_set_function(int_fast16_t pin, enum gpio_function fn)
      |                                                        ^~~~~~~~~~~~~
Compiling .pio/build/release/lib405/LovyanGFX/lgfx/v1/touch/Touch_STMPE610.cpp.o
*** [.pio/build/release/lib405/LovyanGFX/lgfx/v1/platforms/rp2040/common.cpp.o] Error 1

Environment    Status    Duration
-------------  --------  ------------
debug          FAILED    00:00:03.328
release        FAILED    00:00:03.921
----

Did you also get that? How was it fixed?

Trying to compile using PlatformIO Core, version 6.1.16
I tried changing library LovyanGFX to version 1.1.16 (because there where similar problems for others)  to no avail. 

Grateful for any piece to the puzzle. Thanks!

**Comment by PhilippMolitor** [comment]
Thanks for bringing that up! 
I did not encounter that error yet. Not sure why this is happening, but as you noticed yourself it comes from inside the LGFX library, and it looks like some light HAL abstraction...

I just tried to compile a fresh copy, no issues there.

**Comment by AndreasSchutz** [comment]
Hi and thanx for the quick feedback.

Do you have the compile error now?
What was the last mix of versions that you could compile?
Would love to bring the RP2040 to use.

**Comment by PhilippMolitor** [comment]
Did you change any of the compiler flags or target definitions?

**Comment by AndreasSchutz** [comment]
I tried different targets after a while...but basically just a clean "pio run" gives me two errors;

Compiling .pio/build/debug/lib66a/LovyanGFX/lgfx/v1/platforms/spresense/Bus_SPI.cpp.o
.pio/libdeps/debug/LovyanGFX/src/lgfx/v1/platforms/rp2040/common.cpp:78:56: error: use of enum 'gpio_function' without previous declaration
   78 |     bool lgfx_gpio_set_function(int_fast16_t pin, enum gpio_function fn)
      |                                                        ^~~~~~~~~~~~~
.pio/libdeps/debug/LovyanGFX/src/lgfx/v1/platforms/rp2040/common.cpp: In function 'bool lgfx::v1::{anonymous}::lgfx_gpio_set_function(int_fast16_t, int)':
.pio/libdeps/debug/LovyanGFX/src/lgfx/v1/platforms/rp2040/common.cpp:92:16: error: 'iobank0_hw_t' does not name a type; did you mean 'io_bank0_hw_t'?
   92 |       volatile iobank0_hw_t *iobank0_regs = reinterpret_cast<volatile iobank0_hw_t *>(IO_BANK0_BASE);
      |                ^~~~~~~~~~~~
      |                io_bank0_hw_t
.pio/libdeps/debug/LovyanGFX/src/lgfx/v1/platforms/rp2040/common.cpp:93:7: error: 'iobank0_regs' was not declared in this scope; did you mean 'iobank0_hw'?
   93 |       iobank0_regs->io[pin].ctrl = fn << IO_BANK0_GPIO0_CTRL_FUNCSEL_LSB;
      |       ^~~~~~~~~~~~
      |       iobank0_hw


Where I got around the "iobank" error by following the recommendation ('io_bank0_hw_t') but not sure that was a good thing to do.

Like I said... any tip that makes it compile is great!

**Comment by AndreasSchutz** [comment]
And yes.. I try to compile this on an OpenSuSE tumbleweed cli... if that could be an ingredient in the wok! :-D

**Comment by PhilippMolitor** [comment]
sadly i cannot really tell if this is related to this boilerplate..
can you create a MVP project for your target and see if lovyangfx compiles there?

if not, maybe open an issue at the LovyanGFX repo.

**Comment by SHWotever** [comment]
Hi !

I had the same issue, it's indeed tied to the newest rp2040 core.
https://github.com/lovyan03/LovyanGFX/issues/613

To workaround it in the wait the fix is fully public you can use the develop branch :
```https://github.com/lovyan03/LovyanGFX.git#develop```

![image](https://github.com/user-attachments/assets/cb3aaec7-fe92-486c-a6a0-dadd70382aca)

**Comment by PhilippMolitor** [comment]
Thanks for sharing that!

**Comment by ryanayoung** [comment]
> Hi !
> 
> I had the same issue, it's indeed tied to the newest rp2040 core. [lovyan03/LovyanGFX#613](https://github.com/lovyan03/LovyanGFX/issues/613)
> 
> To workaround it in the wait the fix is fully public you can use the develop branch : `https://github.com/lovyan03/LovyanGFX.git#develop`
> 
> ![image](https://private-user-images.githubusercontent.com/2207331/376542920-cb3aaec7-fe92-486c-a6a0-dadd70382aca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4NzcwOTEsIm5iZiI6MTczMDg3Njc5MSwicGF0aCI6Ii8yMjA3MzMxLzM3NjU0MjkyMC1jYjNhYWVjNy1mZTkyLTQ4NmMtYTZhMC1kYWRkNzAzODJhY2EucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDZUMDcwNjMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWVmMmEwNmMxOWYyMzFmMDk2YTY1Zjg0YTg0MGFjZTA1MDMyZGI5OTJiN2RiMWVhOTJkMDgyNzAxMGQyZGMyZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.6OdEgGp_4pfPPki68XhOf-0tfp_rJd5cgiqXnbsHMTY)

Thank you for this. I've been banging my head against a wall all night trying to get this to work.

**Comment by AndreasSchutz** [comment]
I can confirm that it compiles with this in platformio.ini

`lib_deps =

  jrowberg/I2Cdevlib-Core@^1.0.1

  https://github.com/lovyan03/LovyanGFX#develop`

If platformio is stubborn, please delete .pio and retry.
